pyth-network/pyth-agent

Cargo.lock, Cargo.toml
This change will:
- Enable trace/debug logs in release build
- Abort the whole process on a thread panic because there is no way to handle them in the code. The agent usually handles all the errors and never panics
=> Improve cargo build

Cargo.lock, Cargo.toml, config/config.toml, src/agent/solana/exporter.rs
The new pyth agent seems to request 20k CUs for the entire transaction 
https://explorer.solana.com/tx/5zzK9k3pBrL7aH4jMrSrYLjT5AnqbRqu4aE5gK7ozF3MRCzdhhCrcXZu3Fdzo5uUiYF3YdrVAoVfvkJK29rrzuMU
but the old agent seems to request 20k CUs per price update instruction in the transaction:
https://explorer.solana.com/tx/4ASipr9GayTsejvRxLneWiMaZXdbwASo6iGtTYLM3pwwMU1u7X1HZ94K9Lvs2ntNQn45zt1EZ6V9xANwRfyx7kYJ
This explains why the new pyth-agent is running out of compute on mainnet. This PR changes it to request cus per instruction.
=> Request compute units per price update instruction

Cargo.lock, Cargo.toml
As we are starting to roll this out for production the version should become 1.0.0 to indicate that it is a production-ready code.
=> Bump version to 1.0.0

Cargo.lock, Cargo.toml, src/agent.rs, src/agent/metrics.rs, src/agent/store/local.rs, src/lib.rs
This change introduces a simple HTML table for quick reference about individual symbol status. The table is served using a new HTTP endpoint, under "/dashboard". 
[click here](https://imgur.com/a/kRtTGUx)
* The HTTP endpoint is spawned in `agent.rs` together with other async jobs. It reuses the logger and some of the channel tx's.
* Macro recursion limit is raised to 256 (the new type-checked HTML crate is macro-heavy)
* New dependencies
* * typed-html - ergonomic HTML manipulation
* `metrics.rs` - a new metrics- and dashboard oriented module. I plan to also add Prometheus metrics there and I'll probably exile dashboard generation logic to something like `dashboard.rs`. lmk if it's not okay with you.
* The existing Pytest harness continues to pass.
* I verified my code using the example …
=> Add a dashboard in a new metrics.rs module

config/config.toml, integration-tests/poetry.lock, integration-tests/pyproject.toml, integration-tests/tests/test_integration.py, src/agent.rs, src/agent/remote_keypair_loader.rs, src/agent/solana.rs, src/agent/solana/exporter.rs
We open two POST endpoints, `/primary/load_keypair` and `secondary/load_keypair` on a configurable address and port. Each takes a regular Solana keypair in json (`[1, 241, 24, [...], 3]`).  We check that the account holds the configured minimum SOL balance and make it available in the system if the check passes. The endpoints only have an effect if a publisher keypair is not a valid file path on startup. This can be achieved by specifying a name like `""`. A warning is printed in logs when that happens, informing about the service waiting for the key to that network. If the keypair _is_ valid, it is used at all times like before, ignoring the remote key loader completely.
This new system lets you change the key of either network as many times as you wish. This has complicated the design …
=> Add Remote Keypair Loader, a new keypair hotloading mechanism

config/config.toml, src/agent/metrics.rs, src/agent/pythd/adapter.rs, src/agent/solana/oracle.rs, src/agent/store/global.rs
Some of our publishers are concerned about the amount of file descriptors used by the agent process, which could cause problems as the symbol set on chain grows.
We used to look up mapping/product/price accounts using individual Solana RPC requests, opening concurrently a TCP connection per product and another one for each of its prices,
This change replaces these individual product lookups with a single `get_multiple_accounts` call, optionally dividing the bwork into chunks with a new option, `max_lookup_batch_size`. Price lookups are now done in a similar way, by first looking up every first price of each product in a single request, then all second prices (if found) and so on. 
* Tests continue to pass locally - To me this suggests no obvious errors, feel free to suggest any edge cases …
=> oracle.rs: Account -> Entry for clarity, lookup mapping with fewer requests

Cargo.lock, Cargo.toml, src/agent.rs, src/agent/dashboard.rs, src/agent/metrics.rs, src/agent/store/global.rs, src/agent/store/local.rs
This change introduces an initial set of Prometheus metrics:
* Selection of PriceInfo fields from local store
* Selection of PriceAccount fields from global store
* Selection of ProductAccount fields from global store
The metrics are constructed dynamically, depending on the symbols existing in global/local store. Relevant symbol names and pubkeys are marked using labels.
* Tests continue to pass locally
* The full set of metrics is shown when curling the metrics endpoint (localhost:8888/metrics)
* `metrics.rs` - this diff includes moving the simple dashboard do its own module in `dashboard.rs`. Remaining volume of the diff is mostly repetitive registering and updating of the metrics objects. We guard  that all metrics are used with destructuring with errors on unused variable warnings.
=> Prometheus metrics

config/config.toml, src/agent.rs, src/bin/agent.rs
This change should help high-throughput publishers who have seen logger channel errors. The default for the new value is very high, allowing for plenty of messages before reaching the cap. I also added all channel capacity settings to the base config.
=> channel config: add slog buffer capacity, doc capacities in config

config/config.toml, src/agent/metrics.rs
This change makes both localhost:8888 and localhost:8888/dashboard point at the dashboard. Tested manually, integration tests continue to pass
=> metrics.rs: serve dashboard on http root as well

config/config.toml
I overlooked the best spot to put the misplaced remote loader/metrics settings
=> config/config.toml: Move stray options to common optional section

integration-tests/agent_conf.toml, src/agent/metrics.rs
This change polishes metrics appearance. We were using a stray PriceIdentifier for local store prices, which would appear as hex in metrics labels. This converts the identifiers back to pubkeys which print in base58
=> release fixes: identifier to key in metrics,, expose metrics when testsing

integration-tests/tests/test_integration.py, src/agent/solana/oracle.rs
This was left in by mistake when I changed the oracle to share the whole permission set. Previously, the break was used to finish on a price early when we've found that our publisher was permissioned for it.
=> oracle.rs: hotfix: Remove stray loop break

Cargo.lock, Cargo.toml
Bumping the version for the upcoming release. Decided to bump the middle value to 3 because we're providing a new compatible way to interact with the publishing API (batch requests).
=> Cargo.toml, Cargo.lock: Release cutoff

config/config.toml, src/agent/solana/exporter.rs, src/agent/store/local.rs
This change prevents resends of unchanged price data, limited by a delay threshold (5s by default). After the delay passes, the unchanged price will be published anyway to avoid exclusion from aggregate.  This new behavior should help decrease gas costs.
* New option called `<network>.exporter.unchanged_publishing_threshold` (5s by default) - delay after which unchanged updates are allowed.
* Additional filtering rule in `exporter.rs`, using the new option.
* Unit and integration tests continue to pass normally.
=> Unchanged price publishing optimization

Cargo.lock, Cargo.toml, config/config.sample.pythnet.toml, config/config.toml, src/agent/solana/oracle.rs
This change contains small fixes to sample pythnet config, the general `config.toml` and fixes confusing `oracle.rs` log messages. Additionally, package version is bumped to `v2.0.1`
=> v2.0.0 nitpicks

Cargo.lock, Cargo.toml, README.md, src/agent.rs, src/agent/pythd/adapter.rs, src/agent/pythd/api.rs, src/agent/solana.rs, src/agent/solana/exporter.rs, src/agent/solana/oracle.rs, src/agent/store/global.rs, src/agent/store/local.rs, src/bin/agent.rs
We've seen instances of massive error log volumes coming from the agent. This was made significantly worse by the multiline error backtrace output provided from the `anyhow` package. This change alters most `error!()` logs to only use the concise single-line error messages and separates backtrace printing to `debug!()` logs.
Additionally, the error locations tend to be hard to track, which is fixed by adding `use_file_location` to the logger constructor. This should automatically annotate each log message with file/line location information.
Finally, two simple warnings are fixed to clean up compilation log output.
* tests continue to pass locally, 
* The location information is visible in agent logs (see below for example)
* After manually reproducing, the ERRO logs became much shorter, …
=> Make error!() logs shorter, label log location, fix warnings

Cargo.lock, Cargo.toml, config/config.toml, src/agent.rs, src/agent/dashboard.rs, src/agent/metrics.rs, src/agent/pythd/adapter.rs, src/agent/remote_keypair_loader.rs, src/agent/solana.rs, src/agent/solana/exporter.rs, src/agent/solana/oracle.rs, src/agent/store/global.rs, src/bin/agent.rs, src/bin/agent_migrate_config.rs
This PR adds dynamic (exponential) pricing based on staleness of the feeds that the publishers publish. This feature, combined with the recent fees for the price updates causes the spike on fee to last some time before going away.
The second commit contains a little refactoring to fix warnings. Please review commit-by-commit.
=> Use staleness for pricing

Cargo.lock, Cargo.toml, src/agent/solana/exporter.rs
This PR will use the latest slot of the publisher for staleness pricing. The issues that this solve is a publisher publishing for a not yet live feed and also a publisher publishing during market close hours. We can roll out this change to all the publishers without the market-close change and it should be similarly effective.
This change also includes changing the default variables for staleness gap and max paid price for priority fees.
- staleness gap rationale: the rpc might be a bit behind by a few slots. Considering this delay and the exponential pricing this should change the unit price when the feed is really getting stale and doubling if it is still stale.
- max paid price: the lowered value will result in almost 5m priority fee which is very high.
We will modify them later based …
=> fix: use publisher latest slot for staleness based pricing

integration-tests/tests/test_integration.py, src/agent/market_hours.rs, src/agent/metrics.rs, src/agent/pythd/adapter.rs, src/agent/solana/exporter.rs, src/agent/solana/oracle.rs
This change builds on the previously introduced market hours format and applies it to the agent's publishing logic. The extraction, parsing and distribution of the market hours info piggy-backs the existing publisher permissions flow. This felt appropriate because of a shared idea: "Does on-chain data say this is okay to publish?". You'll quickly see that a big part of the changeset is a series of additions to the publisher permissions processing logic. In the same spirit, the changes to state simply add market hours to the detected permissioned symbols that are checked when filtering prices.
* `oracle.rs` - Attempt to parse market hours when looking up products, fall back to 24/7 if failing po parse. Specifically, print a warning if the market hours field is defined but could not be …
=> exporter: Use market hours information in price filtering

Cargo.lock, Cargo.toml, src/agent/solana/exporter.rs
One publisher has tried the previous version. I noticed that often they fall behind on some specific symbols by not publishing themself and that causes a sudden increase in priority once they publish it. That is why i am also considering the aggregate slot for the pricing. I'm also excluding the non-live feeds because publishers are often more unstable on them.
=> fix: use both latest publisher and aggregate slot for dynamic pricing

Cargo.lock, Cargo.toml, config/config.sample.pythnet.toml, config/config.toml, src/agent/solana/exporter.rs, src/agent/solana/oracle.rs
The old max cost for total transaction didn't make sense as everything is handled in the per compute unit pricing and in the grand scheme of things we care about the price of an update not a transaction (which can have between 1 to 12 updates). This will make the behaviour simpler. Also, there were cases where the tx had little updates and the per compute unit price went very high and it impacted other publishers.
This is a non-breaking change because the config reader ignores incorrect fields (I checked it).
The default cap is also changed to 10 million as there have been spikes up to 6 million in the past. If publishers have working ws + short pulls. For this reason I changed the default for pull duration to 5 seconds which can have bad impact on Pythnet but the network load is not that …
=> refactor: improve price cap configuration

Cargo.lock, Cargo.toml, src/agent/solana/exporter.rs
This change removes a check in the code that does not allow multiple updates within the same timestamp (second based) pass through. `last_info.timestamp` is always less than or equal to `info.timestamp`. So, this condition `last_info.timestamp < info.timestamp` filters newer updates in the same timestamp and essentially caps our publishing frequency to 1s. It was intended to work for Solana but the publishing frequency itself takes care of it. This change might result in increased Sol burn but the action to reduce it should be reducing the frequency. Please note that in some filterings after, the same update prices are ignored so most of the fee savings should remain there.
=> fix: remove unnecessary fresh price filtering

config/config.sample.pythnet.toml
In the agent code, there are different async actors. There is one actor for getting the prices from the publisher and there is another one to export what is already available to Pythnet/Solana. Some publishers continuously send their updates to agent and they have no problem. However, some publishers wait for a notification from the agent to send their update. The problem with having both at the same frequency is that there is a decent chance that these two intervals don't match with each other and cause occasions on which exporter doesn't have any data or skips one data and it increases the overall latency of our network. This PR changes the notification interval to 100ms to minimize the added latency.
=> Change notify price schedule interval duration from 400ms to 100ms

README.md
smol and arguably pedantic change. add build-essential installation to readme steps. rustup makes an assumption thats the C linker is already installed. on the fresh ubuntu 22.04 system i am building on build-essential wasn't installed leading to a `cc linker not found` error on rust compilation.
installing build-essential ensures the gcc tool chain is on the box.
=> add build-essential to dependencies install step in readme

src/agent/pythd/adapter.rs, src/agent/remote_keypair_loader.rs, src/agent/solana/exporter.rs
Adapter sends price update notifications to the subscriber API connection actor but at the same time the subscriber actor can get blcoked on receiving messages (e.g. product info) from Adapter. If the channel from Adapter to the subscriber gets full the Adapter can get blocked and this results in a deadlock. This situation propagates and queues messages in other actors and WS messages from the clients will grow in an unbounded queue that results in a constant memory growth (leak).
This change simply makes the Adaptor to subscriber API connection nonblocking by dropping messages if the channels are full.
=> fix: remove adapter <> api deadlock

Cargo.lock, Cargo.toml, src/agent/solana/exporter.rs
The existing code creates futures for publish_batch with delays to spread the rpc load evenly in the publish interval however due to the Rust async design those futures do not get started unless they are awaited. This results in additional deterministic latency of almost the publish_interval especially for the publishers who publish many prices.
This change removes the code as even the intended behaviour adds latency and disrupts the publish interval (the last publish_batch can block the actor loop).
=> fix: remove delay in publish_batch execution

Cargo.lock, Cargo.toml, src/agent/dashboard.rs, src/bin/agent_migrate_config.rs
This change updates the agent dependencies to their most recent version. Please see the inline comments on the code changes due to the upgrades for an explanation.
=> chore: update dependencies

config/config.sample.pythnet.toml
100ms notify_sched_interval is causing problems for the publishers and this change reverts it back to 400ms.
The exact reason for the problem is still unknown but we think their slow clients (forked from our example publisher) and poor agent design cause this issue. A major refactor is going to improve agent bottlenecks and also remove notifications  to make sure it doesn't add unnecessary overhead to the clients.
=> chore: update Pythnet sample config

Cargo.lock, Cargo.toml, src/agent.rs, src/agent/pythd/adapter.rs, src/agent/pythd/adapter/api.rs, src/agent/pythd/api/rpc.rs, src/agent/pythd/api/rpc/get_all_products.rs, src/agent/pythd/api/rpc/get_product.rs, src/agent/pythd/api/rpc/get_product_list.rs, src/agent/pythd/api/rpc/subscribe_price.rs, src/agent/pythd/api/rpc/subscribe_price_sched.rs, src/agent/pythd/api/rpc/update_price.rs, src/agent/store/global.rs
This PR refactors the Adapter to remove the running service component. The goal behind this is to remove the channel communication between the adapter and other components, instead, Adapter now acts as an API. The Adapter API currently is a single nameless trait with all functionality combined, this change will allow splitting that API out into relevant components to better isolate functionality. For now though, this just moves the entire API into a temporary trait called `AdapterApi`, in future PR's, `adapter/` will become `state/` and the relevant functionality will be broken out.
Apart from the `AdapterApi` and channel removal, all other changes are mechanical, just propagating the change through the codebase.
Some changes that occurred during this refactoring:
- Tests from rpc.rs are …
=> refactor: migrate adapter service to api

src/agent/solana.rs, src/agent/solana/exporter.rs, src/agent/solana/oracle.rs
Fixes heap growth if `Exporter::update_our_prices` is not called as often as updates. 
Running `agent --config config/config.sample.pythtest.toml` would previously appear to "leak" memory quite quickly over time as `Exporter::update_our_prices` was not being called to drain the channel. The existing publisher permissions is bounded, but bounded at 10k would take a long time to fill and has a huge memory ceiling.
The fix is straightforward as the receiver side only ever used the latest value sent anyway, replacing the mpsc bounded channel with a watch channel produces equivalent behaviour but with a drastically reduced memory ceiling as it holds a single clone of the `publisher_permissions` map no matter the behaviour/frequency of the rx side.
=> Send publisher permissions using a watch channel to address heap growth

Cargo.lock, Cargo.toml, config/config.toml, src/agent/solana/exporter.rs
This change updates the CU limit to make sure that price updates with more than 32 publishers have enough CU. Number 38k is obtained based on adjusting `test_full_publisher_set` test on the oracle to run in multiple rounds with random price updates to make sure worst case sorting is reached. Unfortunately there was no way to test it with CPI to accumulator (message buffer) and that number is taken based on current tx usage and the extra buffer is there because there are some extra logic in the oracle for oracle as well and the CU limit is not applied in transaction scheduling.
=> chore: update max compute unit config and bump version

Cargo.lock, Cargo.toml, integration-tests/tests/test_integration.py, src/agent/dashboard.rs, src/agent/metrics.rs, src/agent/pythd/adapter.rs, src/agent/pythd/adapter/api.rs, src/agent/solana/exporter.rs, src/agent/solana/oracle.rs, src/agent/store/local.rs
This PR introduces support for a new product metadata key `publish_interval`. It will only allow the publish of a new price after this interval has passed since last updated price.
=> feat: add publish_interval logic

Cargo.lock, Cargo.toml, config/config.sample.pythnet.toml, config/config.sample.pythtest.toml, config/config.toml, src/agent.rs, src/agent/config.rs, src/agent/pyth/rpc.rs, src/agent/pyth/rpc/get_all_products.rs, src/agent/pyth/rpc/get_product.rs, src/agent/pyth/rpc/get_product_list.rs, src/agent/pyth/rpc/subscribe_price.rs, src/agent/pyth/rpc/subscribe_price_sched.rs, src/agent/pyth/rpc/update_price.rs, src/agent/services/exporter.rs, src/agent/services/notifier.rs, src/agent/services/oracle.rs, src/agent/state/api.rs, src/agent/state/exporter.rs, src/agent/state/keypairs.rs, src/agent/state/oracle.rs, src/agent/state/transactions.rs, src/bin/agent.rs
This PR enhances tracing by introducing the `#[instrument]` macro to more functions and adding additional fields to the current span in `get_product.rs`, `subscribe_price.rs`, and `subscribe_price_sched.rs`. This approach is async safe as it maintains the reference to the current span without manual enter/exit, ensuring the tracing context is preserved across await points. We should avoid manual enter/exit tracing logs already handled by `#[instrument]`, and any custom spans should be cautious of this behavior to avoid manual span entry.
=> improve tracing coverage

Cargo.lock, Cargo.toml, src/bin/agent.rs
Apparently if we pass env filter in an array with the other layers it won't be executed first (to act as a filter). This change fixes that by explicitly adding it before.
=> fix: use env filter properly

Cargo.toml, rust-toolchain.toml, src/agent/services/exporter.rs, src/agent/state/exporter.rs
During refactoring the async spawning of the transaction sender was removed but not added back.
=> fix: spawn transaction senders in exporter

Cargo.lock, Cargo.toml, config/config.toml, src/agent/config.rs, src/agent/pyth/rpc.rs, src/bin/agent.rs
We might send thousands of messages per second to the clients and `send` method flushes each request which might take a longer time. This change changes our responses and notifications to `feed` and flushes the messages based on a configured interval (default: 100ms).
There is a small refactor of a config in the previous changes to make it match our configuration style.
=> fix: feed rpc responses and notifications instead of send and flush

Cargo.lock, Cargo.toml, src/agent/state/local.rs
This log can be helpful for publishers who want to confirm whether their price updates are being received by the agent or not.
=> chore: add price_info log in local store update

.github/workflows/rust.yaml
GitHub deprecating Ubuntu 20.04:
https://github.com/actions/runner-images/issues/11101
=> Bump Ubuntu release

Cargo.lock, Cargo.toml, src/agent/legacy_schedule.rs, src/agent/market_schedule.rs, src/agent/metrics.rs, src/agent/pyth.rs, src/agent/state.rs, src/agent/state/api.rs, src/agent/state/exporter.rs, src/agent/state/global.rs, src/agent/state/local.rs, src/agent/state/oracle.rs
- Using `Arc<PriceEntry>` and `Arc<ProductEntry>` in `UpdateProductAccountUpdate` and `Update::PriceAccountUpdate` to decrease the size difference between the variants.
- Using `Arc<PriceEntry>` and `Arc<ProductEntry>` in maps to reduce clone time by only cloning the reference
- Replacing imutable strings by `SmolStr`
- Remove unnecessary `clone` on `Copy`
- Fix audit issue:
```sh
Crate:     rustls                                                                                               
Version:   0.21.10                                                                                              
Title:     `rustls::ConnectionCommon::complete_io` could fall into an infinite loop based on network input      
Date:      2024-04-19 …
```
=> Reduce memory usage, faster copies and other small improvements

Cargo.lock, Cargo.toml, config/config.toml, src/agent/services/oracle.rs, src/agent/state/oracle.rs
While running the agent  version `v.2.12.1`, it crashed after some time with an out of memory issue, having to be killed by the OS.
The machine I was using has 48GB of RAM
It was happening for both mainet and testnet.
I did not see anything particularly special about the resources it was using:
But the number of tasks seems large.
One can see 7721 tasks while a lot of them are idle for some time.
After observing it, the number of tasks would increase with time until the point it would, the binary would be killed.
The idle tasks are created here https://github.com/pyth-network/pyth-agent/blob/main/src/agent/services/oracle.rs#L132 as can be seen in the image, where the subscriber is handling the `handle_price_account_update`.
That line is crating tokio tasks without keeping track of the …
=> Fix tokio task leak

Cargo.lock, Cargo.toml
use the new pyth sdk-solana that contains a bug fix for iterating over product attributes. the older version might go beyond the size of the attributes (and show old attribute residuals instead).
We got a report that symbol is the old symbol on agent and it looked impossible because the metadata was updated everywhere. What was happening was that on `Crypto.Index.CRT/USD` token, `symbol` is defined two times if you look at the raw account data below and the older sdk would parse all the account regardless of the size. [This](https://github.com/pyth-network/pyth-sdk-rs/pull/123) PR has fixed it.
```
0000:   d4 c3 b2 a1  02 00 00 00  02 00 00 00  09 01 00 00   ................
0010:   b2 fb 54 96  6d 4d 30 af  bb 77 cc 9d  ce 9d 43 c5   ..T.mM0..w....C.
0020:   2f 0f 57 5e  7d 41 dc ab  6f …
```
=> fix: handle product attributes properly

config/config.sample.pythnet.toml, config/config.sample.pythtest.toml, config/config.toml, integration-tests/tests/test_integration.py
program key
This change was made in the codebase already but didn't make it into the samples. Now that there's 2 program_key entries this makes it clear what they are used for
=> Fix: Update config samples with more descriptive pyth_oracle_ for

Cargo.lock, Cargo.toml, src/agent/services/lazer_exporter.rs
Initial attempt at publishing a SignedLazerTransaction on each publish interval..
=> feat: publish signed Lazer transactions

Cargo.lock, Cargo.toml, config/config.sample.pythnet.toml, config/config.sample.pythtest.toml, config/config.toml, src/agent.rs, src/agent/services/exporter.rs, src/agent/services/keypairs.rs, src/agent/services/oracle.rs, src/agent/solana.rs, src/agent/state/exporter.rs, src/agent/state/oracle.rs, src/agent/state/transactions.rs, src/agent/utils.rs, src/agent/utils/rpc_multi_client.rs
Change rpc_url to rpc_urls and for all calls, cycle through them until first success.
=> feat: RPC redundancy

src/agent/services/lazer_exporter.rs
Simply use the id bytes as a lookup key. Cosmetic fixes.
=> fix: hermes id handling
